
### POST Ask price demo step 1
# @timeout 600
POST http://localhost:8080/chatWithMemory
Content-Type: application/json

{
  "prompt": "price"
}

###

### POST Ask price demo step 2
# @timeout 600
POST http://localhost:8080/chatWithMemory
Content-Type: application/json

{
  "prompt": "btc and eth"
}

### POST Ask price demo step 3
# @timeout 600
POST http://localhost:8080/chatWithMemory
Content-Type: application/json

{
  "prompt": "more other coins"
}

### POST Ask price demo step 4
# @timeout 600
POST http://localhost:8080/chatWithMemory
Content-Type: application/json

{
  "prompt": "solana"
}

### POST Ask portfolio demo
# @timeout 600
POST http://localhost:8080/chat
Content-Type: application/json

{
  "prompt": "what is my portfolio?"
}

### POST Ask portfolio with more detail demo
# @timeout 600
POST http://localhost:8080/chat
Content-Type: application/json

{
  "prompt": "what is my portfolio and list my holding with quantity"
}


### POST Ask tickets demo
# @timeout 600
POST http://localhost:8080/chat
Content-Type: application/json

{
  "prompt": "show my tickets"
}

### POST Ask tickets with details demo
# @timeout 600
POST http://localhost:8080/chat
Content-Type: application/json

{
  "prompt": "show my tickets with related withdrawal"
}

### POST Ask tickets with details demo 2
# @timeout 600
POST http://localhost:8080/chat
Content-Type: application/json

{
  "prompt": "show my tickets with related withdrawal and wallet address"
}
