
### POST
# @timeout 600
POST http://localhost:8080/chatWithMemory
Content-Type: application/json

{
  "prompt": "price"
}

###

### POST
# @timeout 600
POST http://localhost:8080/chatWithMemory
Content-Type: application/json

{
  "prompt": "btc and eth"
}

### POST
# @timeout 600
POST http://localhost:8080/chatWithMemory
Content-Type: application/json

{
  "prompt": "more other coins"
}

### POST
# @timeout 600
POST http://localhost:8080/chatWithMemory
Content-Type: application/json

{
  "prompt": "solana"
}

### POST
# @timeout 600
POST http://localhost:8080/chat
Content-Type: application/json

{
  "prompt": "what is my portfolio?"
}

### POST
# @timeout 600
POST http://localhost:8080/chat
Content-Type: application/json

{
  "prompt": "what is my portfolio and list my holding with quantity"
}


### POST
# @timeout 600
POST http://localhost:8080/chat
Content-Type: application/json

{
  "prompt": "show my tickets"
}

### POST
# @timeout 600
POST http://localhost:8080/chat
Content-Type: application/json

{
  "prompt": "show my tickets with related withdrawal"
}

### POST
# @timeout 600
POST http://localhost:8080/chat
Content-Type: application/json

{
  "prompt": "show my tickets with related withdrawal and wallet address"
}
